### ISSUE TITLE
/admin/auth 404 not found

### ISSUE THREAD

**Issue by morganizeit** [googleanalytics/google-analytics-super-proxy#18]
I want to setup my own proxy but I can't get past square 1.

When I run locally I get 404 not found for http://localhost:8080/admin/auth.  Same for /admin.  I deployed via the app engine with the same result.

The app is running, http://localhost:8080 results in "Hello world!".  I can see this is the default in main.py... but I don't know how to troubleshoot request routing in a Python app.

Cheers,
Morgan.

**Comment by morganizeit** [comment]
Aha!  Resolved.

When adding this app to the GoogleAppEngineLauncher point it at the /src directory.  Otherwise it creates a "hello world" controller and nothing in the src directory is used.

Cheers,
Morg.

**Comment by prikkprikkprikk** [comment]
I would like to add: Do not enter the project ID when adding the app to GoogleAppEngineLauncher! If you do, it adds a new folder within the src folder, and you'll get the same result: Hello World, and /admin not found.
