### ISSUE TITLE
Missing Something

### ISSUE THREAD

**Issue by workerbee22** [googleanalytics/google-analytics-super-proxy#2]
Followed the instructions to the letter. But after setting up AppEngine Hosting, then trying to hit:  

https://your-application-id.appspot.com/admin

get a 404 error. Hitting just:

https://your-application-id.appspot.com 

does show 'Hello World' in the browser.

AppEngine Dashboard shows an error on the /admin URI at 100%. Seems like I've missed something or instructions are missing something.

> > > Reviewed for a 4th time and realized that when using the AppEngine Launcher I used the 'Create New Application' instead of 'Add Existing Application' option. Then re-deployed to AppEngine and tried the admin URL again:

https://your-application-id.appspot.com/admin

Then got the correct 'authorization message' as expected, rather than the 404 error. So not an issue. But suggest the readme file under the AppEngine Launcher instructions also note the use of this option. I only picked this up when reading the instructions for the Local setup. CLOSED.

**Comment by pfrisella** [comment]
Make sure you replace **_your-application-id**_ with the actual App Engine Id you registered during the setup. Also, you should be able to use the **_Add Existing Application**_ option.

**Comment by HappyMeal** [comment]
so... I have the same problem.  Can't access admin panel - either locally or on appspot.  Hello World works no problem - but 404 on admin.  I've tried admin, admin/auth.  My paths and id's are correct in the config files.

**Comment by pfrisella** [comment]
Take a look at https://github.com/googleanalytics/google-analytics-super-proxy/issues/18

**Comment by HappyMeal** [comment]
I love you
