### ISSUE TITLE
Service Down?

### ISSUE THREAD

**Issue by ChipPappas** [googleanalytics/google-analytics-super-proxy#40]
This has been working for several months flawlessly, but this evening I got this error:
**Error: Server Error**
**The server encountered an error and could not complete your request.**

**Please try again in 30 seconds.**

Most recently I'm not getting that error, just a blank page with a title of :

**uncaught application failure**

Any thoughts?

**Comment by wcoonan** [comment]
Hi, ChipPappas. Was this resolved for you? If so, please share how you fixed it. I'm having the same issue, which started yesterday afternoon as well.

**Comment by ChipPappas** [comment]
My problem turned out to be a quota issue with my appspot account. (my poor programming caused a loop which called for data multiple times).

I found this by looking at the logs in my appspot account.

**Comment by wcoonan** [comment]
Thanks! I'll guess mine is a similar issue.
